### ISSUE TITLE
Nice stuff and a question

### ISSUE THREAD

**Issue by AlanDrake** [MartyShepard/DOSBox-Optionals#3]
Thank you for creating this build, I love to attempt giving old games their original look.

Does Dosbox have a setting for doubling up lowres VGA modes? Unlike CGA/EGA monitors, VGA ones doubled the resolution which caused the iconic double scanlines, it may sound useless but for shaders to handle it 1:1 there should be a way to reproduce this behavior. So far I'm using `normal2x` as a workaround which looks good enough.

Here, as a present a fine tuned shader to give off a VGA monitor vibe, tested on a 1080p display.
[crt-lottes_vga.zip](https://github.com/MartyShepard/DOSBox-Optionals/files/4295904/crt-lottes_vga.zip)

**Comment by MartyShepard** [comment]
Hello, thanks for this. :)

i put your shader in my next upcoming Releases.
To your Question. Dosbox doubles low res screens in pixels. Scanlines are not emulated. For that come and exitst shaders. That's why I don't like Scumm. Too Pixelate. Mame makes it great again.

greetings

**Comment by DwarfFighterCleric** [comment]
Well I have a question but I don't want to create another thread. Do you know of any easy-to-get game or application (the smallest file size possible) in order for me to test out if my Dosbox has the appropriate 3D accelerated drivers configured correctly? Are there any "test applications" for 3dfx and Glide out there? I don't need to run anything above 640x480, I just need 3D drivers because software render makes my CPU too slow and overheats.

**Comment by MartyShepard** [comment]
The 3DFX CPU soft mode is already very slow by default. (Old MAME code). The problem is not your hardware. That's the code.

PS: Sorry for the late reply
